# Generated by Django 5.1 on 2024-09-08 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0002_alter_policy_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
