# Generated by Django 5.1 on 2024-09-08 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0003_policy_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='policy',
            options={'ordering': ['position'], 'verbose_name_plural': 'Policies'},
        ),
    ]
