# Generated by Django 5.1 on 2024-09-22 17:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0006_alter_policy_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='title',
            field=models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(5)]),
        ),
    ]
