# Generated by Django 5.1 on 2024-10-06 10:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0007_alter_policy_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='content',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(100)]),
        ),
        migrations.AlterField(
            model_name='policy',
            name='title',
            field=models.CharField(max_length=150, validators=[django.core.validators.MinLengthValidator(5)]),
        ),
    ]
