# Generated by Django 5.1 on 2024-09-10 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_addon'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlineitem',
            name='addons',
            field=models.ManyToManyField(blank=True, related_name='order_lineitems', to='checkout.addon'),
        ),
    ]
