# Generated by Django 5.1 on 2024-09-10 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0007_orderlineitem_addons'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderlineitem',
            name='addons',
        ),
    ]
