# Generated by Django 5.1 on 2024-09-10 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0008_remove_orderlineitem_addons'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlineitem',
            name='addons',
            field=models.ManyToManyField(blank=True, to='checkout.addon'),
        ),
    ]
