# Generated by Django 5.1 on 2024-09-10 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0009_orderlineitem_addons'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='add_ons',
            field=models.ManyToManyField(blank=True, related_name='orders', to='checkout.addon'),
        ),
    ]
