# Generated by Django 5.1 on 2024-09-10 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0010_order_add_ons'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderlineitem',
            name='addons',
        ),
    ]
