# Generated by Django 5.1 on 2024-09-10 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0011_remove_orderlineitem_addons'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='add_ons_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
