# Generated by Django 5.1 on 2024-09-10 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0013_alter_order_add_ons_cost_alter_order_delivery_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlineitem',
            name='lineitem_total',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=12),
        ),
    ]
