# Generated by Django 5.1 on 2024-10-04 05:36

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_alter_product_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/dmqcpnmy9/image/upload/v1728019511/22204581_6605550_yg5rag.jpg', max_length=255, verbose_name='image'),
        ),
    ]
