# Generated by Django 5.1 on 2024-09-02 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_method', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliverymethod',
            old_name='cost',
            new_name='rate',
        ),
        migrations.RemoveField(
            model_name='deliverymethod',
            name='description',
        ),
        migrations.RemoveField(
            model_name='deliverymethod',
            name='weight_max',
        ),
        migrations.RemoveField(
            model_name='deliverymethod',
            name='weight_min',
        ),
    ]
