# Generated by Django 5.1 on 2024-09-10 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_method', '0002_rename_cost_deliverymethod_rate_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliverymethod',
            options={'ordering': ['position']},
        ),
        migrations.AddField(
            model_name='deliverymethod',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
